name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest-xdist pytest-timeout pytest-html
          playwright install chromium
          playwright install-deps chromium

      - name: Run tests
        env:
          PYTHONUNBUFFERED: 1
        run: |
          pytest -n 3 --timeout=600 --html=report.html --self-contained-html

      
      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: report.html
